### ISSUE TITLE
DCMHattention

### ISSUE THREAD

**Issue by Wangjinhong1998** [Caiyun-AI/DCFormer#3]
Congratulations on your significant breakthrough. I have a question for you: Can the DCMH attention mechanism mentioned in this article be applied to the transformer structure used in models like CLIP? I noticed that its implementation seems rather complex, and I have not been able to fully grasp it yet...

**Comment by hilbertmeng** [comment]
Thank you for your recognition. Yes, image-encoder(ViT) and text-encoder(Text Transformer) in CLIP can also adopt DCMHA. It is independent of attention mask, and can be incorporated into both causal attention(GPT-like) and self-attention(BERT-like).
