### ISSUE TITLE
a bug in the  HLO->LLVM IR lowering

### ISSUE THREAD

**Issue by szrrr04** [Caiyun-AI/DCFormer#5]
I tried to reproduce your training code using the JAX framework, and I changed the dataset to the lm1b dataset (so I modified the data processing function to _tfds_data_processing.py, which is already present in your folder). Without modifying any data types, I encountered thousands of "Floating-point arithmetic operators only work with floating-point types!" errors during the run. Additionally, it prompted "This probably indicates a bug in the HLO -> LLVM IR lowering. Rerun with --xla_dump_to to get the IR." Could you please help me understand the cause of this issue?
![image](https://github.com/user-attachments/assets/b3ccf71b-dbf4-4ae6-878c-b118af3d5914)
![image](https://github.com/user-attachments/assets/2a49b63e-e49d-4e17-b600-3ad4598c2bdf)
I've omitted thousands of lines of errors between the two images I've uploaded to you. The original training log file might be unable to upload due to formatting issues. I would be extremely grateful if you could help me resolve this issue!

**Comment by szrrr04** [comment]
I noticed there was also a stack trace error mixed in.
*** Begin stack trace ***
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	_PyObject_MakeTpCall
	
	_PyEval_EvalFrameDefault
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	_PyFunction_Vectorcall
	
	
	
	
	
	
	
	
	_PyObject_MakeTpCall
	
	
	_PyObject_MakeTpCall
	_PyEval_EvalFrameDefault
	_PyFunction_Vectorcall
	PyObject_Call
	_PyEval_EvalFrameDefault
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	_PyFunction_Vectorcall
	PyObject_Call
	_PyEval_EvalFrameDefault
	_PyFunction_Vectorcall
	
	
	_PyEval_EvalFrameDefault
	_PyFunction_Vectorcall
	PyObject_Call
	_PyEval_EvalFrameDefault
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	
	PyObject_Call
	_PyEval_EvalFrameDefault
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	_PyFunction_Vectorcall
	
	
	_PyEval_EvalFrameDefault
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	
	PyEval_EvalCode
	
	
	
	_PyRun_SimpleFileObject
	_PyRun_AnyFileObject
	Py_RunMain
	Py_BytesMain
	__libc_start_main
	
*** End stack trace ***

Per train step, total TFLOPs will be 207.49, split as 90.45% learnable weight flops and 9.55% attention flops
jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/u2022212091/u2022212091/DCFormer/jax/MaxText/train.py", line 551, in <module>
    app.run(main)
  File "/home/u2022212091/.conda/envs/20240816/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/u2022212091/.conda/envs/20240816/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/home/u2022212091/u2022212091/DCFormer/jax/MaxText/train.py", line 547, in main
    train_loop(config)
  File "/home/u2022212091/u2022212091/DCFormer/jax/MaxText/train.py", line 471, in train_loop
    state, metrics = p_train_step(
jaxlib.xla_extension.XlaRuntimeError: INTERNAL: RET_CHECK failure (external/xla/xla/service/cpu/cpu_compiler.cc:1048) !llvm::verifyModule(llvm_module, &err_stream) Invalid LLVM IR before optimizations:

**Comment by Lisennlp** [comment]
Your problem seems to be a data type problem. You can check whether the type of the data you entered is correct. The correct one should be:
![image](https://github.com/user-attachments/assets/ce1a2d53-872b-4a1d-aa9d-a1acfe0915f8)
Secondly, check whether the jax you installed is compatible with your cuda version. We tested the version:
![image](https://github.com/user-attachments/assets/85141898-bbc9-449e-892e-332cfad2bb18)
and jax and jaxlib version is：
![image](https://github.com/user-attachments/assets/63bff72d-cd9a-4b96-a591-30c4486a60fd)

If the above methods still cannot solve your problem, you can try to use our dataset (https://huggingface.co/datasets/Caiyun-AI/Pile_tfrecord/tree/main) to see if it can run. Since the entire dataset is relatively large, you can use only one file for the experiment.
The following is a log of an experiment I just ran according to the readme：
![image](https://github.com/user-attachments/assets/785d1077-ca3a-46a6-aec6-2672ffa7c82e)

I hope the above can help you.

**Comment by szrrr04** [comment]
Thank you! I checked, and first of all, the type of the data I entered is correct. I didn’t modify anything related to data types.

Secondly, all the package versions I installed are correct, exactly as specified in the requirements_gpu. However, I found that my CUDA version might not be right because I’m using the school's supercomputing platform. I noticed that the current CUDA version on the platform is pointing to 11.8, but I don’t have the permission to change it, so I might need to contact the administrator later.

Without changing the CUDA version, I tried switching the dataset to Pile, but I still encountered the same issue. This makes it almost certain that the problem is related to the CUDA version.

I’d like to ask, since the current CUDA versions available on the supercomputing platform are 12.2 and 12.4, can I ask the administrator to change the current version to point to 12.2 instead of having them install version 12.1? Does the CUDA compiler version have to be exactly 12.1, or is any version above 12.1 acceptable?
![image](https://github.com/user-attachments/assets/87a38fb0-874e-4ab0-96a1-3feafe7e1945)

**Comment by Lisennlp** [comment]
When I switched the jax version to jax[cuda12_pip]==0.4.25, I have reproduced your problem. After this problem occurred, I upgraded the jax version to jax[cuda12_pip]==0.4.30, and it can run successfully again. Therefore, as long as the jax and cuda versions are compatible, it is not only suitable for cuda12.1. Therefore, you can adapt to your cuda version by changing the jax version.

**Comment by szrrr04** [comment]
Okay, thank you, I understand. So, you're saying I can keep my CUDA version at 11.8 and just adjust my JAX version, right?

**Comment by Lisennlp** [comment]
Yes, besides that, you can also try jax[cuda12_pip]==0.4.30 on cuda 12.2 and 12.4.

**Comment by szrrr04** [comment]
Thank you very much! I tried upgrading JAX to 0.4.30 while keeping CUDA at 11.8 (since contacting the administrator is a bit inconvenient), and that solved the problem!

**Comment by szrrr04** [comment]
I'm sorry, I've encountered a new problem. What could be the cause of this? Is it possible that it's due to insufficient memory? Currently, I have 120GB of memory allocated on the cluster. If I'm training on a chunk of the Pile dataset, which is approximately 2GB, should this memory be sufficient?
![image](https://github.com/user-attachments/assets/faedb9ce-be66-4364-9fc2-bf0525a3fce2)
![image](https://github.com/user-attachments/assets/b047d4e2-6cd3-4119-a481-ec1d03df8430)

**Comment by szrrr04** [comment]
I encountered this issue when I was running the training for the second time, trying to resume from a checkpoint.

**Comment by Lisennlp** [comment]
Hello, your error does not seem to be out of video memory, and your 120G video memory is enough to train a 6B model with length = 2048. I suspect that the jax version you installed is still wrong, and it seems that the gpu cannot be obtained. You can try running python -c 'import jax; print(len(jax.devices()))' in the command line to see if jax can obtain the target tpu devices. If the output tpu number is 0, it means that it cannot be obtained.

**Comment by Lisennlp** [comment]
Hello, your error does not seem to be out of HBM, and your 120G HBM is enough to train a 6B model with length = 2048. I suspect that the jax version you installed is still wrong, and it seems that the gpu cannot be obtained. You can try running python -c 'import jax; print(len(jax.devices()))' in the command line to see if jax can obtain the tpu devices. If the output tpu number is 0, it means that it cannot be obtained.

**Comment by Lisennlp** [comment]
If it is due to the cuda and jax version, you can try to install jax[cuda12_pip]==0.4.30. And set your cuda version to cuda12.2 or 12.4. You do not need to reinstall cuda. ​​If you do not know how to set it, you can refer to: https://www.cnblogs.com/huadongw/p/15193247.html

**Comment by szrrr04** [comment]
Thank you for your help! I successfully set up CUDA 12.2 following the link you provided. However, when I tried to install jax[cuda12_pip]==0.4.30, I found that it said it couldn't find pip. Is this because I modified the PATH? How can I resolve this issue?
![image](https://github.com/user-attachments/assets/723242a7-5614-43d6-a243-45d7520fd31f)
![image](https://github.com/user-attachments/assets/ff68c690-4080-47c1-bd1f-30f4b71bfc4e)

**Comment by szrrr04** [comment]
I think this problem has already been solved by me. I added my PIP_OR_PYTHON_PATH to the PATH, and now my pip can be found! Is this the correct solution? Additionally, if I have already set this in the .bashrc file, do I still need to specify the PIP_OR_PYTHON_PATH again in the train.sh script? Is it okay to do this, or could it cause any conflicts?
![image](https://github.com/user-attachments/assets/28029e6d-e4cd-4981-bc8d-b9301b23e2cc)
![image](https://github.com/user-attachments/assets/585f9928-263c-4f9a-82a9-9aab616f832a)

**Comment by Lisennlp** [comment]
Yes, you have overwritten the path of your python or pip. You can add your python and pip paths in .bashrc
Assume that the python or pip dir is：/usr/local/bin/
example:
```bash
# add Python path
export PATH=/usr/local/bin/python3.10:$PATH
# add pip path
export PATH=/usr/local/bin:$PATH
```

**Comment by Lisennlp** [comment]
> I think this problem has already been solved by me. I added my PIP_OR_PYTHON_PATH to the PATH, and now my pip can be found! Is this the correct solution? ![image](https://private-user-images.githubusercontent.com/143482508/359328431-28029e6d-e4cd-4981-bc8d-b9301b23e2cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxMzEwOTcsIm5iZiI6MTcyNDEzMDc5NywicGF0aCI6Ii8xNDM0ODI1MDgvMzU5MzI4NDMxLTI4MDI5ZTZkLWU0Y2QtNDk4MS1iYzhkLWI5MzAxYjIzZTJjYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMFQwNTEzMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZjA4ODhiZmZhNWI3NzAwODMzNmUyNzZkOGY1NGI1ZDlmOTAzN2NjYzE0NzAxY2Y3ODdiZmRkMzExNGQ2ZGIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.luKO9eplb3MCZVBNqawRCN98GgSL6trHrdObbhELAD8)

Yes, you are right!

**Comment by szrrr04** [comment]
Hello, I think I’m ready now! I have set the CUDA environment variables in the ~/.bashrc file, and it’s for CUDA 12.2（asP1）. Additionally, I’ve successfully installed jax[cuda12_pip]==0.4.30（asP2）. I should be all set now, right? I have one last question: yesterday, when I hadn’t figured out how to set up CUDA 12.2, I used the conda install nvidia/label/cuda-12.1.1::cuda-tools command in my virtual environment, which installed a bunch of packages that start with cuda_. （asP3）Is this a problem? Should I remove them, or can I just leave them as they are?
![image](https://github.com/user-attachments/assets/d1081a59-f554-4bb1-95f4-c9bf9bf48b70)
![image](https://github.com/user-attachments/assets/e9b9ef53-0302-4819-8500-dbb7c2dbb57c)
![image](https://github.com/user-attachments/assets/5b7165ef-58e4-4e5b-b772-2706eeebd996)

**Comment by Lisennlp** [comment]
All are fine. The extra ones just take up more memory. If you don't need them, you can selectively uninstall them.

**Comment by szrrr04** [comment]
Finally, it's all working!! Everything went smoothly. Thank you so, so much!
![image](https://github.com/user-attachments/assets/1e9fc62f-377b-4f1a-a3d4-f8d7a343febd)
And I think I finally understand the specific reason behind my previous errors and why it seemed to work yesterday but didn’t use the GPU. Earlier, when I encountered data type errors, I hadn’t set the CUDA environment variables in my bashrc file, but my JAX and JAXlib versions were based on CUDA 11, which caused the errors. Last night, I upgraded my JAX and JAXlib to JAX[cuda11_pip]==0.4.30, but during installation, it warned me that there was no CUDA version, so I ended up installing the non-CUDA versions of JAX and JAXlib. Since I didn’t have a CUDA compiler configured, the code ran but couldn’t utilize the GPU. Now that I’ve correctly configured everything, it’s all working fine!

Thank you so much again! Without your help, I would have struggled for much longer! Best wishes~

**Comment by szrrr04** [comment]
However, I noticed that on the current supercomputing platform at my school, I used 16 CPU cores and 2 GPUs, but the steps/s is only 0.361. I calculated that if I were to train for the 10,000,000 steps specified in the configuration file, it would still take a very long time. Can this 10,000,000 steps be shortened appropriately, or will my code automatically stop training once the metrics stabilize?
And one more question: If my training is interrupted due to a timeout, the code will automatically load the checkpoint files the next time I resume training, correct? I don’t need to manually configure anything, right? Thank you very much~

**Comment by Lisennlp** [comment]
The 10 milions step is not the total number of steps you are training, just to keep it going, so you need to stop the program manually, for example when loss drops to a certain value. In addition, if the program is unexpectedly interrupted, the latest model will automatically load after you restart, and the data will be read from the last interrupt.
